### ISSUE TITLE
BAT error

### ISSUE THREAD

**Issue by dbsthrdl** [Jire/Overwatcheat#114]
Native library (win32-x86-64/interception.dll) not found in resource path (Overwatcheat 3.5.0.jar)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
        at com.overwatcheat.nativelib.DirectNativeLib.<init>(DirectNativeLib.kt:27)
        at com.overwatcheat.nativelib.interception.Interception.<init>(Interception.kt:25)
        at com.overwatcheat.nativelib.interception.Interception.<clinit>(Interception.kt:25)
        at com.overwatcheat.Mouse.<clinit>(Mouse.kt:36)
        at com.overwatcheat.aimbot.AimBotThread.performAim(AimBotThread.kt:105)
        at com.overwatcheat.aimbot.AimBotThread.useAimData(AimBotThread.kt:74)
        at com.overwatcheat.aimbot.AimBotThread.run(AimBotThread.kt:48)
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
                ... 9 more
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
                ... 9 more
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:264)
                ... 9 more
        Suppressed: java.io.IOException: Native library (win32-x86-64/interception.dll) not found in resource path (Overwatcheat 3.5.0.jar)
                at com.sun.jna.Native.extractFromResourcePath(Native.java:1119)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
                ... 9 more

Which part is wrong?

**Comment by Qrivatem** [comment]
use java jdk 15 ( or change ur version to it with 
setx -m JAVA_HOME "C:\Progra~1\Java\jdk1.8.0_XX"
)
