### ISSUE TITLE
Not working in OW2

### ISSUE THREAD

**Issue by pmoe7** [Jire/Overwatcheat#131]
Hi,

This is no longer working in OW2. I modified the code a bit to debug the issue, it turns out it is not able to get aimData. So either the colorMatch process is broken (Blizzard changed color values for Magenta or did something to block it) or screen grabbing is broken.

**Comment by petrsoudek** [comment]
Hi, I tried to change the colors to the new from OW2, but something else seems to be wrong.

**Comment by pmoe7** [comment]
I did some more debugging. After changing the target colours to include this particular magenta colour (#F903FA) the aim bot works but in a broken way; it just aims up and up and with the overlay, it shows the square all over the screen. This means everything except the colorMatch is working fine.

**Comment by C0DE4ME** [comment]
> I did some more debugging. After changing the target colours to include this particular magenta colour (#F903FA) the aim bot works but in a broken way; it just aims up and up and with the overlay, it shows the square all over the screen. This means everything except the colorMatch is working fine.

i have same issue
anyone have solution??

**Comment by pmoe7** [comment]
No solution yet. Hopefully, we can figure it out soon.

**Comment by SylveonBottle** [comment]
I increased target_color_tolerance to 80 and was able to get a purple box that showed across the selected area.
Decreasing this to 79 no longer shows the box.

It's almost as if a high enough color tolerance allows gdigrab to detect the color black. Is gdigrab only receiving a black input?

**Comment by Wintreist** [comment]
> I increased target_color_tolerance to 80 and was able to get a purple box that showed across the selected area. Decreasing this to 79 no longer shows the box.
> 
> It's almost as if a high enough color tolerance allows gdigrab to detect the color black. Is gdigrab only receiving a black input?

I tried it, it didn't work out for me, purple doesn't appear

**Comment by pmoe7** [comment]
Hey lads,

I went ahead and developed the entire aimbot from scratch in Python. It's not as good as this one but about 60% there. I am working on improving it. If anyone is interested in collab, let me know

**Comment by petrsoudek** [comment]
> Hey lads,
> 
> I went ahead and developed the entire aimbot from scratch in Python. It's not as good as this one but about 60% there. I am working on improving it. If anyone is interested in collab, let me know

Hello pmoe7,

I am interested in collab for sure. I have a great set of skills in C#, but already made some projects in py, it shouldnt be a problem.

**Comment by ztmzzz** [comment]
I found it didn't work with obs, but it can work well by capture overwatch.
`window_title_search=Overwatch`

**Comment by xtherk** [comment]
> I found it didn't work with obs, but it can work well by capture overwatch. `window_title_search=Overwatch`

Do not use ` window_ title_ Search=Overwatch `  Soon you will get a black screen, and then aim will not work.

**Comment by ztmzzz** [comment]
> > I found it didn't work with obs, but it can work well by capture overwatch. `window_title_search=Overwatch`
> 
> Do not use `window_ title_ Search=Overwatch` Soon you will get a black screen, and then aim will not work.

or use  `window_ title_ Search=desktop`

**Comment by xtherk** [comment]
> > > I found it didn't work with obs, but it can work well by capture overwatch. `window_title_search=Overwatch`
> > 
> > 
> > Do not use `window_ title_ Search=Overwatch` Soon you will get a black screen, and then aim will not work.
> 
> or use `window_ title_ Search=desktop`

yeah, You should use window_ title_ Search=desktop.

see https://github.com/Jire/Overwatcheat/issues/129#issuecomment-1236617940

**Comment by pmoe7** [comment]
> I somehow get it to work but it is so snappy. Very effective when in short range

Do you mind sharing what you did differently?

**Comment by pmoe7** [comment]
ok, guys yeah go in the FrameGrabber file in the source code and change this line:

`filename: String = "title=${FrameWindowFinder.findWindowTitle(windowTitleSearch)}"`

to this
`filename: String =  if ("desktop".equals( windowTitleSearch)) windowTitleSearch else "title=${FrameWindowFinder.findWindowTitle(windowTitleSearch)}"`

and change this in Overcheat.CFG file
`window_title_search=desktop` 

then it should be working

**Comment by Wintreist** [comment]
> Хорошо, ребята, да, перейдите в файл FrameGrabber в исходном коде и измените эту строку:
> 
> `filename: String = "title=${FrameWindowFinder.findWindowTitle(windowTitleSearch)}"`
> 
> к этому `filename: String = if ("desktop".equals( windowTitleSearch)) windowTitleSearch else "title=${FrameWindowFinder.findWindowTitle(windowTitleSearch)}"`
> 
> и измените это в файле Overcheat.CFG `window_title_search=desktop`
> 
> тогда должно работать

Exception in thread "main" java.lang.Exception: Could not find window title with search: "desktop"
        at com.overwatcheat.framegrab.FrameWindowFinder.findWindowTitle(FrameWindowFinder.kt:54)
        at com.overwatcheat.framegrab.FrameGrabber.<init>(FrameGrabber.kt:30)
        at com.overwatcheat.Overwatcheat.main(Overwatcheat.kt:52)

**Comment by Wintreist** [comment]
Перекомпилить не надо?

**Comment by xtherk** [comment]
> Перекомпилить не надо?

Recompile

**Comment by pmoe7** [comment]
Play the game in full screen

**Comment by rmgnum** [comment]
> > I somehow get it to work but it is so snappy. Very effective when in short range
> 
> Do you mind sharing what you did differently?

I had problems with compiling the latest version it gives giving me FAILURE: Build failed with an exception Task 'overwatcheat' not found in root project 'overwatcheat'. so I tried compiling older version

• Copied the settings of version 3.5 to 3.4.1
• Playing in borderless window (if that helps)
• Change color blind settings enemy to magenta 

and works. Very effective on short range like reaper, orisa, Mei. Not effective on long range and semi automatic guns like cassidy

**Comment by pmoe7** [comment]
For anyone interested, here is my aimBot in Python. It is not 100% accurate but it's pretty decent and there's definitely a lot of room for improvement. 

https://github.com/pmoe7/OW-AimAssist

**Comment by pmoe7** [comment]
I compiled the Python code to an EXE so its super simple to download and run now.


> For anyone interested, here is my aimBot in Python. It is not 100% accurate but it's pretty decent and there's definitely a lot of room for improvement.
> 
> https://github.com/pmoe7/OW-AimAssist

**Comment by Wintreist** [comment]
If someone does solve the problem, write here

**Comment by Wintreist** [comment]
> If someone does solve the problem, write here

my personal problem was solved, I did not change the color of the opponents to mangeta

**Comment by Flowing8175** [comment]
If your monitor have Freesync(or GSync) modes e.g. normal or ultimate, toggle it to another and reboot ur computer. that helps me when "no error but no working" situation.
