### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by laozhouya** [Jire/Overwatcheat#137]
[gdigrab @ 000001ba7cd72700] Can't find window 'New Issue �� Jire/Overwatcheat ����1 ���� - ���- Microsoft? Edge', aborting.
[gdigrab @ 000001ba7cd72700] Can't find window 'New Issue �� Jire/Overwatcheat ����1 ���� - ���- Microsoft? Edge', aborting.
Exception in thread "Frame Grabber" org.bytedeco.javacv.FFmpegFrameGrabber$Exception: avformat_open_input() error -5: Could not open input "title=New Issue · Jire/Overwatcheat 和另外 1 个页面 - 个人 - Microsoft? Edge". (Has setFormat() been called?) (For more details, make sure FFmpegLogCallback.set() has been called.)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:921)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:846)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:841)
        at com.overwatcheat.framegrab.FrameGrabberThread.run(FrameGrabberThread.kt:30)

**Comment by laozhouya** [comment]
[gdigrab @ 000001a77f9c2700] Capture area (860,440),(1060,640) extends outside window area (0,0),(960,480)Capture area (860,440),(1060,640) extends outside window area (0,0),(960,480)Exception in thread "Frame Grabber" org.bytedeco.javacv.FFmpegFrameGrabber$Exception: avformat_open_input() error -5: Could not open input "title=Overwatcheat 3.5.0". (Has setFormat() been called?) (For more details, make sure FFmpegLogCallback.set() has been called.)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:921)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:846)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:841)
        at com.overwatcheat.framegrab.FrameGrabberThread.run(FrameGrabberThread.kt:30)

**Comment by laozhouya** [comment]
> [gdigrab @ 000001ba7cd72700] Can't find window 'New Issue �� Jire/Overwatcheat ����1 ���� - ���- Microsoft? Edge', aborting. [gdigrab @ 000001ba7cd72700] Can't find window 'New Issue �� Jire/Overwatcheat ����1 ���� - ���- Microsoft? Edge', aborting. Exception in thread "Frame Grabber" org.bytedeco.javacv.FFmpegFrameGrabber$Exception: avformat_open_input() error -5: Could not open input "title=New Issue · Jire/Overwatcheat 和另外 1 个页面 - 个人 - Microsoft? Edge". (Has setFormat() been called?) (For more details, make sure FFmpegLogCallback.set() has been called.) at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:921) at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:846) at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:841) at com.overwatcheat.framegrab.FrameGrabberThread.run(FrameGrabberThread.kt:30)
