### ISSUE TITLE
The libs and overwatcheat.jar file does not exist error?

### ISSUE THREAD

**Issue by moooookelll-ldd** [Jire/Overwatcheat#147]
ype-safe project accessors is an incubating feature.
> Task :overwatcheat FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':overwatcheat'.
> kotlin.io.NoSuchFileException: C:\Users\Name\Downloads\Overwatcheat-4.0.0.tar\Overwatcheat-4.0.0\Overwatcheat-4.0.0\build\libs\Overwatcheat-4.0.0.jar: The source file doesn't exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 975ms
16 actionable tasks: 1 executed, 15 up-to-date
Press any key to continue . . .

**Comment by moooookelll-ldd** [comment]
yep tell me of you find a fix

**Comment by dongerlel** [comment]
Same here Overwatcheat-4.0.0.jar doesn't exist.

**Comment by Stormzilla1886** [comment]
got 0 clue what the issue is, i tried different versions of java on different machines but still nothing, wiped a machine tested it and got same error

**Comment by xtherk** [comment]
lease download the Zip from https://github.com/xtherk/Overwatcheat/archive/refs/heads/main.zip link and rebuild or wait PR merge.

**Comment by laozhouya** [comment]
> 请下载Zip从 https://github.com/xtherk/Overwatcheat/archive/refs/heads/main.zip 链接并重新构建或等待PR合并。


错误: 加载主类 org.jire.overwatcheat.Main 时出现 LinkageError
        java.lang.UnsupportedClassVersionError: org/jire/overwatcheat/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 59.0
请按任意键继续. . .

**Comment by laozhouya** [comment]
Exception in thread "main" java.lang.NumberFormatException: For input string: "160      "
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:668)
        at java.base/java.lang.Integer.parseInt(Integer.java:786)
        at org.jire.overwatcheat.settings.IntSetting.parse(IntSetting.kt:26)
        at org.jire.overwatcheat.settings.Settings.read(Settings.kt:63)
        at org.jire.overwatcheat.settings.Settings.read(Settings.kt:53)
        at org.jire.overwatcheat.settings.Settings.read$default(Settings.kt:53)
        at org.jire.overwatcheat.Main.main(Main.kt:34)
请按任意键继续. . .

**Comment by xtherk** [comment]
@laozhouya  160后面多了个空格...

**Comment by xtherk** [comment]
> java.lang.UnsupportedClassVersionError: org/jire/overwatcheat/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 59.0


Upgrade your jdk to jdk11+

**Comment by laozhouya** [comment]
升级到17了有影响吗？

**Comment by RigidDynamics** [comment]
> Please download the Zip from https://github.com/xtherk/Overwatcheat/archive/refs/heads/main.zip link and rebuild or wait PR merge.

Does this fix the source file not found?

**Comment by xtherk** [comment]
> > Please download the Zip from https://github.com/xtherk/Overwatcheat/archive/refs/heads/main.zip link and rebuild or wait PR merge.
> 
> Does this fix the source file not found?

yep

**Comment by dongerlel** [comment]
> Please download the Zip from https://github.com/xtherk/Overwatcheat/archive/refs/heads/main.zip link and rebuild or wait PR merge.

![image](https://user-images.githubusercontent.com/12804761/196406080-a7386481-28b6-4488-af52-1c0ecf47bee4.png)
thank you it works :)

**Comment by RigidDynamics** [comment]
> > > Please download the Zip from https://github.com/xtherk/Overwatcheat/archive/refs/heads/main.zip link and rebuild or wait PR merge.
> > 
> > 
> > Does this fix the source file not found?
> 
> yep, you can try

![Screenshot (68)](https://user-images.githubusercontent.com/89148553/196495995-ab0895ff-76b4-4ddd-8623-788f81880ff4.png)

Nope, still the same issue with your link.

**Comment by hw1992** [comment]
![image](https://user-images.githubusercontent.com/29779220/196685669-1e4b91fa-3699-42af-97d9-2769f01b1297.png)
@

>

**Comment by YinMoL** [comment]
> 請下載Zip從 https://github.com/xtherk/Overwatcheat/archive/refs/heads/main.zip 連結並重新構建或等待PR合併。


連結無法下載
The link cannot be downloaded

**Comment by Rang108** [comment]
> 

请问这步怎么解决的哇 JAVA版本不一致的问题

**Comment by DragonFlamez** [comment]
> Please download the Zip from https://github.com/xtherk/Overwatcheat/archive/refs/heads/main.zip link and rebuild or wait PR merge.

I got the same problem as this dude, but I can't download from this link. Can you put it back up?
