### ISSUE TITLE
Error upon launching build for first time

### ISSUE THREAD

**Issue by rhys4AC** [Jire/Overwatcheat#166]
Type-safe project accessors is an incubating feature.
> Task :overwatcheat FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':overwatcheat'.
> kotlin.io.NoSuchFileException: G:\Overwatcheat-4.0.0\Overwatcheat-4.0.0\build\libs\Overwatcheat-4.0.0.jar: The source file doesn't exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 821ms
16 actionable tasks: 1 executed, 15 up-to-date
Press any key to continue . . .

**Comment by rhys4AC** [comment]
![image](https://user-images.githubusercontent.com/116378262/197248932-dc62fe20-2da1-4d1a-b4d7-b4120cf20ef0.png)

**Comment by rhys4AC** [comment]
have got the build going but am now getting this error in the actual overwatcheat

Exception in thread "Frame Grabber" org.bytedeco.javacv.FFmpegFrameGrabber$Exception: av_find_input_format() error: Could not find input format "gdigrab". (For more details, make sure FFmpegLogCallback.set() has been called.)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:881)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:849)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:844)
        at org.jire.overwatcheat.framegrab.FrameGrabberThread.run(FrameGrabberThread.kt:30)
