### ISSUE TITLE
Exception in thread "Frame Grabber

### ISSUE THREAD

**Issue by raze013** [Jire/Overwatcheat#170]
Exception in thread "Frame Grabber" org.bytedeco.javacv.FFmpegFrameGrabber$Exception: av_find_input_format() error: Could not find input format "gdigrab". (For more details, make sure FFmpegLogCallback.set() has been called.)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:881)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:849)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:844)
        at org.jire.overwatcheat.framegrab.FrameGrabberThread.run(FrameGrabberThread.kt:30)

**Comment by m0nnk3y** [comment]
i also have the same issue, anyone know how to fix this?

**Comment by aocun** [comment]
i also have the same issue, anyone know how to fix this?

**Comment by akurol128** [comment]
me too，anyone fix this？
