### ISSUE TITLE
Exception in thread "Frame Grabber"

### ISSUE THREAD

**Issue by Jnllee** [Jire/Overwatcheat#189]
Exception in thread "Frame Grabber" org.bytedeco.javacv.FFmpegFrameGrabber$Exception: av_find_input_format() error: Could not find input format "gdigrab". (For more details, make sure FFmpegLogCallback.set() has been called.)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:881)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:849)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:844)
        at org.jire.overwatcheat.framegrab.FrameGrabberThread.run(FrameGrabberThread.kt:30)

**Comment by Jnllee** [comment]
Need help please

**Comment by deceased1** [comment]
i guess no one is getting help

**Comment by Bulbxsaur** [comment]
Someone PLEASE help, cant seem to find out why this is happening, have had this issue for hours.
