### ISSUE TITLE
interception folder location?

### ISSUE THREAD

**Issue by kairis1** [Jire/Overwatcheat#195]
I have installed it and restarted my pc but this error comes up when I start 

[gdigrab @ 0000012c0485e4c0] Found window Overwatch, capturing 256x256x32 at (1592,592)
Input #0, gdigrab, from 'title=Overwatch':
  Duration: N/A, start: 1668285746.054863, bitrate: 62927 kb/s
  Stream #0:0: Video: bmp, bgra, 256x256, 62927 kb/s, 30 fps, 1000k tbr, 1000k tbn
Exception in thread "Aim Bot" java.lang.UnsatisfiedLinkError: Unable to load library 'interception':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/interception.dll) not found in resource path (Overwatcheat 4.0.0.jar)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:307)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:467)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:409)
        at org.jire.overwatcheat.nativelib.DirectNativeLib.<init>(DirectNativeLib.kt:27)
        at org.jire.overwatcheat.nativelib.interception.Interception.<init>(Interception.kt:25)
        at org.jire.overwatcheat.nativelib.interception.Interception.<clinit>(Interception.kt)
        at org.jire.overwatcheat.Mouse.<clinit>(Mouse.kt:36)
        at org.jire.overwatcheat.aimbot.AimBotThread.performAim(AimBotThread.kt:107)
        at org.jire.overwatcheat.aimbot.AimBotThread.useAimData(AimBotThread.kt:76)
        at org.jire.overwatcheat.aimbot.AimBotThread.run(AimBotThread.kt:50)
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:197)
                ... 9 more
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:210)
                ... 9 more
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:270)
                ... 9 more
        Suppressed: java.io.IOException: Native library (win32-x86-64/interception.dll) not found in resource path (Overwatcheat 4.0.0.jar)
                at com.sun.jna.Native.extractFromResourcePath(Native.java:1145)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:281)
                ... 9 more

**Comment by kairis1** [comment]
solved issue
after installing the interception 
i needed to place the interception.dll and interception.lib file into the overwatchcheat 4.0.0 folder

**Comment by orhnxd** [comment]
cant find interception file
