### ISSUE TITLE
Failed to Capture image (error 5) 4.0.0

### ISSUE THREAD

**Issue by ZuccoMode362** [Jire/Overwatcheat#201]
Changing the window_title_search to Fullscreen Projector does not do anything as I'm not using obs. 

Error when window_title_search=Overwatch:

[gdigrab @ 000001fa1560dcc0] Found window Overwatch, capturing 256x256x32 at (832,412)
[gdigrab @ 000001fa1560dcc0] Failed to capture image (error 5)
[gdigrab @ 000001fa1560dcc0] Could not find codec parameters for stream 0 (Video: bmp, none, 262198 kb/s): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, gdigrab, from 'title=Overwatch':
  Duration: N/A, bitrate: 262198 kb/s
    Stream #0:0: Video: bmp, none, 262198 kb/s, 125 fps, 1000k tbr, 1000k tbn, 1000k tbc
[gdigrab @ 000001fa1560dcc0] Failed to capture image (error 5)
Exception in thread "Frame Grabber" java.lang.NullPointerException: frame must not be null
        at com.overwatcheat.framegrab.FrameGrabberThread.run(FrameGrabberThread.kt:34)

Error  when window_title_search=Fullscreen Projector:

Exception in thread "main" java.lang.Exception: Could not find window title with search: "Fullscreen Projector"
        at com.overwatcheat.framegrab.FrameWindowFinder.findWindowTitle(FrameWindowFinder.kt:54)
        at com.overwatcheat.framegrab.FrameGrabber.<init>(FrameGrabber.kt:30)
        at com.overwatcheat.Overwatcheat.main(Overwatcheat.kt:52)
Press any key to continue . . .
![Screenshot 2022-12-01 174446](https://user-images.githubusercontent.com/119634541/205174942-7e4dac0e-f102-4bf5-b77e-235c0680098f.jpg)
![Overwatch error](https://user-images.githubusercontent.com/119634541/205174943-51cb842a-ca51-4692-811c-aef90b2cb071.jpg)
![Fullscreen Projector Error](https://user-images.githubusercontent.com/119634541/205174944-5c1a965a-5b06-457f-aa12-a4b8c92d8957.jpg)

Here are my settings that I copy pasted onto a note doc becayse .cfg is not accepted here:
[settings.txt](https://github.com/Jire/Overwatcheat/files/10136733/settings.txt)

**Comment by Denver3D** [comment]
I got the same issue any update how to make it works ?

**Comment by Krenity** [comment]
put the game in windowed mode not fullscreen
