### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Cannot open library: interception

### ISSUE THREAD

**Issue by danzddev** [Jire/Overwatcheat#209]
So it's throwing me this error:
Exception in thread "Aim Bot" java.lang.ExceptionInInitializerError
        at org.jire.overwatcheat.Mouse.<clinit>(Mouse.kt:33)
        at org.jire.overwatcheat.aimbot.AimBotThread.performAim(AimBotThread.kt:108)
        at org.jire.overwatcheat.aimbot.AimBotThread.useAimData(AimBotThread.kt:77)
        at org.jire.overwatcheat.aimbot.AimBotThread.run(AimBotThread.kt:53)
Caused by: java.lang.IllegalArgumentException: Cannot open library: interception
        at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:235)
        at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:199)
        at org.jire.overwatcheat.nativelib.interception.InterceptionPanama.<clinit>(InterceptionPanama.kt:26)
        ... 4 more

And it's all fine, I built it, colors are magenta, and interception is working because i'm using an .ahk script that uses autohotintercept and it goes just fine, any idea what could be causing this?

**Comment by Flowing8175** [comment]
did u put interception.dll file in built overwatcheat folder? I mean, C:\Users\smth\Downloads\Overwatcheat 5.1.0\**build** folder.

**Comment by Flowing8175** [comment]
I got the same error, and I fixed it by putting in the right architecture interception driver. You can check it by hitting Win+Pause (if ur keyboard don't have the key, search **device info** at windows search). Check ur architecture there, then hack should work.
