### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Flowing8175** [Jire/Overwatcheat#216]
[main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/C:/Users/userbruh/Downloads/Overwatcheat-5.1.0/build/Overwatcheat%205.1.0/Overwatcheat%205.1.0.jar
Exception in thread "Aim Bot" java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 8
        at net.openhft.affinity.LockInventory.acquireLock(LockInventory.java:135)
        at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:305)
        at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:189)
        at org.jire.overwatcheat.aimbot.AimBotThread.run(AimBotThread.kt:63)
Info: [gdigrab @ 0000028a9c542000] Found window **_전체화면 프로젝터 (소스) - 게임 캡쳐_** (note: this window is obs projector but in my language), capturing 400x400x32 at (1520,520)
Info: Input #0, gdigrab, from 'title=전체화면 프로젝터 (소스) - 게임 캡쳐':

Info:   Duration:
Info: N/A
Info: , start:
Info: 1673616525.983545
Info: , bitrate:
Info: 460838 kb/s
Info:

Info:   Stream #0:0
Info: : Video: bmp, bgra, 400x400, 460838 kb/s
Info: ,
Info: 90 fps,
Info: 1000k tbr,
Info: 1000k tbn
Info:

**Comment by Flowing8175** [comment]
wrote wrong number at cpu smth so ye it fixed
