### ISSUE TITLE
PLEASE HELP ME 

### ISSUE THREAD

**Issue by Rainwaterjimi** [Jire/Overwatcheat#226]
[main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/C:/Users/rainw/OneDrive/Desktop/Overwatcheat-5.1.0%20(3)/Overwatcheat-5.1.0/build/Overwatcheat%205.1.0/Overwatcheat%205.1.0.jar
[Aim Bot] INFO net.openhft.affinity.AffinityLock - Assigning cpu 2 to Thread[#53,Aim Bot,9,main] on thread id 12832
[Aim Bot] WARN net.openhft.affinity.impl.WindowsJNAAffinity - Tried to set affinity to {2} but was {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15} you may have in sufficient access rights
Error: [gdigrab @ 0000020ae8749680] Capture area (1152,592),(1408,848) extends outside window area (0,0),(1320,720)
Error: Capture area (1152,592),(1408,848) extends outside window area (0,0),(1320,720)
Exception in thread "Frame Grabber" org.bytedeco.javacv.FFmpegFrameGrabber$Exception: avformat_open_input() error -5: Could not open input "title=Overwatcheat 5.1.0". (Has setFormat() been called?) (For more details, make sure FFmpegLogCallback.set() has been called.)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:975)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:903)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:898)
        at org.jire.overwatcheat.framegrab.FrameGrabberThread.run(FrameGrabberThread.kt:30)
Exception in thread "Toggle UI" java.lang.ExceptionInInitializerError
        at org.jire.overwatcheat.Keyboard.pressKey(Keyboard.kt:49)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.toggleUI(ToggleUIThread.kt:44)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.run(ToggleUIThread.kt:35)
Caused by: java.lang.IllegalArgumentException: Cannot open library: interception
        at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:235)
        at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:199)
        at org.jire.overwatcheat.nativelib.interception.Interception.<clinit>(Interception.kt:26)
        ... 3 more
my OW 5.1.0 says this please help

**Comment by Flowing8175** [comment]
dont use fullscreen mode at overwatch use **windowed fullscreen** mode

**Comment by shpaass** [comment]
Please clarify what the problem is and then change the title accordingly.
