### ISSUE TITLE
Flick shoot dont work what is wrong with my config pls help

### ISSUE THREAD

**Issue by Flowing8175** [Jire/Overwatcheat#230]
tracking is working well but flick mode does click LMB, but doesnt move aim, randomly does. (1 time in 6~10 shoot?maybe)

My cfg file:
aim_key=2
aim_mode=1
fps=75
aim_duration_millis=3
aim_duration_multiplier_base=0.4
aim_duration_multiplier_max=1 (I tried 0, 0.4, 1, 2, 10)
aim_max_move_pixels=150
aim_jitter_percent=0
aim_min_target_width=6
aim_min_target_height=6
box_width=400 (I tried 256, 350, 400, 450)
box_height=400 (same)
max_snap_divisor=1
target_color_tolerance=6
window_title_search=Overwatch
mouse_id=11
keyboard_id=1
aim_offset_x=1.00
aim_offset_y=0.75 (tried 0.8, 0.75 which is default value)
flick_shoot_pixels=200 (tried 5, 6, 8, 200 but same happenes)
flick_pause_duration=900 (widow charge shot)
toggle_in_game_ui=true
toggle_key_codes=12,5A
aim_precise_sleeper_type=1
aim_cpu_thread_affinity_index=-1

if some values are wrong pls tell me i love flickshot characters.....

**Comment by brtj** [comment]
Which release do you use? Because I got issue:
```
Exception in thread "Toggle UI" java.lang.ExceptionInInitializerError
        at org.jire.overwatcheat.Keyboard.pressKey(Keyboard.kt:49)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.toggleUI(ToggleUIThread.kt:44)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.run(ToggleUIThread.kt:35)
Caused by: java.lang.IllegalArgumentException: Cannot open library: interception
        at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:235)
        at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:199)
        at org.jire.overwatcheat.nativelib.interception.Interception.<clinit>(Interception.kt:26)
        ... 3 more
```

**Comment by Flowing8175** [comment]
~~Do you mean you want me to help you? If so please make a new issue table. If I understand it wrong sry bc I suck at English lol~~


Edit: ah shit I got your meaning lol

I have no error message like you but your situation seems that you typed the wrong key code in your config, did you change the toggle_ui_key setting?




F**k my brain.

**Comment by Flowing8175** [comment]
> Which release do you use? Because I got issue:
> ```
> Exception in thread "Toggle UI" java.lang.ExceptionInInitializerError
>         at org.jire.overwatcheat.Keyboard.pressKey(Keyboard.kt:49)
>         at org.jire.overwatcheat.aimbot.ToggleUIThread.toggleUI(ToggleUIThread.kt:44)
>         at org.jire.overwatcheat.aimbot.ToggleUIThread.run(ToggleUIThread.kt:35)
> Caused by: java.lang.IllegalArgumentException: Cannot open library: interception
>         at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:235)
>         at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:199)
>         at org.jire.overwatcheat.nativelib.interception.Interception.<clinit>(Interception.kt:26)
>         ... 3 more
> ```

And I'm using 5.1.0 version.
