### ISSUE TITLE
got an error opening start overwatchcheat 5.1.0 today

### ISSUE THREAD

**Issue by sleepspapi** [Jire/Overwatcheat#244]
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/foreign/MemorySession
        at org.jire.overwatcheat.nativelib.User32Panama.<clinit>(User32Panama.kt:26)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.<init>(ToggleUIThread.kt:29)
        at org.jire.overwatcheat.Main.main(Main.kt:73)
Caused by: java.lang.ClassNotFoundException: java.lang.foreign.MemorySession
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
![image_2023-03-26_210011952](https://user-images.githubusercontent.com/129005411/227801345-2ce9cc93-1148-4b53-bbc6-c3b29eeee597.png)

**Comment by felipepm10** [comment]
I have the same problem, did you manage to solve it?

**Comment by wuzhenhui0328** [comment]
Try Java JDK19

**Comment by Merl1nas** [comment]
didnt work, am i doing ssomething wrong?

**Comment by CRaZe12345** [comment]
yeah, had it installed already still didn't work
![image](https://user-images.githubusercontent.com/129446265/228960772-ebb790b5-9dc2-4729-8fc6-4cc18766442a.png)

**Comment by rxzkie** [comment]
> Try Java JDK19

ty thats work forme

**Comment by yoToby** [comment]
yo i have the same problem?
