### ISSUE TITLE
NOT LAUNCHING ERROR IN DESC

### ISSUE THREAD

**Issue by Merl1nas** [Jire/Overwatcheat#245]
[main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/C:/Users/nexas/Downloads/Overwatcheat-main/Overwatcheat-5.1.0/build/Overwatcheat%205.1.0/Overwatcheat%205.1.0.jar
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/foreign/MemorySession
        at org.jire.overwatcheat.nativelib.User32Panama.<clinit>(User32Panama.kt:26)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.<init>(ToggleUIThread.kt:29)
        at org.jire.overwatcheat.Main.main(Main.kt:73)
Caused by: java.lang.ClassNotFoundException: java.lang.foreign.MemorySession
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more
Press any key to continue . . .

**Comment by Wilppaa** [comment]
got the same problem rn
