### ISSUE TITLE
i get this error when i try to run the cheat

### ISSUE THREAD

**Issue by Wilppaa** [Jire/Overwatcheat#246]
[main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/C:/Users/viljami%20kotoneva/Desktop/Overwatcheat-main/build/overwatcheat/overwatcheat.jar
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/foreign/MemorySession
        at org.jire.overwatcheat.nativelib.User32Panama.<clinit>(User32Panama.kt:26)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.<init>(ToggleUIThread.kt:29)
        at org.jire.overwatcheat.Main.main(Main.kt:73)
Caused by: java.lang.ClassNotFoundException: java.lang.foreign.MemorySession
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more

**Comment by nb52** [comment]
I get the exact same error. Can someone help.

**Comment by ek271** [comment]
have u got it fixed
