### ISSUE TITLE
error -5 but weird

### ISSUE THREAD

**Issue by tcmmi** [Jire/Overwatcheat#258]
What does that error mean and how would I fix it?
I use JDK 19 and v5.1.0 of this cheat

PS. Error appears when I open `Start Overwatcheat 5.1.0.bat`
I also don't use OBS.

> [main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/C:/Users/klapr/Desktop/Overwatcheat-5.1.0/Overwatcheat-5.1.0/build/Overwatcheat%205.1.0/Overwatcheat%205.1.0.jar
> [Aim Bot] INFO net.openhft.affinity.AffinityLock - Assigning cpu 2 to Thread[#42,Aim Bot,9,main] on thread id 18712
> [Aim Bot] WARN net.openhft.affinity.impl.WindowsJNAAffinity - Tried to set affinity to {2} but was {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11} you may have in sufficient access rights
> Error: [gdigrab @ 000002171b769780] Capture area (832,412),(1088,668) extends outside window area (0,0),(0,0)
> Error: Capture area (832,412),(1088,668) extends outside window area (0,0),(0,0)
> Exception in thread "Frame Grabber" org.bytedeco.javacv.FFmpegFrameGrabber$Exception: avformat_open_input() error -5: Could not open input "title=Overwatch". (Has setFormat() been called?) (For more details, make sure FFmpegLogCallback.set() has been called.)
>         at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:975)
>         at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:903)
>         at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:898)
>         at org.jire.overwatcheat.framegrab.FrameGrabberThread.run(FrameGrabberThread.kt:30)

**Comment by Flowing8175** [comment]
It seems u didn't use borderless fullscreen mode in Overwatch.
If you used it correctly set the cpu affenity thing to -1 at cfg file.
