### ISSUE TITLE
how to solve?

### ISSUE THREAD

**Issue by LucasBosko** [Jire/Overwatcheat#288]
Hi, I need your help

Exception in thread "Aim Bot" java.lang.NoClassDefFoundError: java/lang/foreign/MemorySession
at org.jire.overwatcheat.nativelib.User32Panama.<clinit>(User32Panama.kt:26)
at org.jire.overwatcheat.Keyboard.keyState(Keyboard.kt:25)
at org.jire.overwatcheat.Keyboard.keyPressed(Keyboard.kt:27)
at org.jire.overwatcheat.aimbot.AimBotThread.run(AimBotThread.kt:47)
Caused by: java.lang.ClassNotFoundException: java.lang.foreign.MemorySession
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
... 4 more
Info: [gdigrab @ 000001fab617d8c0] Found window Overwatch, capturing 256x256x32 at (832,412)

Info: Input #0, gdigrab, from 'title=Overwatch':

Info: Duration:
Info: N/A
Info: , start:
Info: 1689705746.710618
Info: , bitrate:
Info: 125855 kb/s
Info:

Info: Stream #0:0
Info: : Video: bmp, bgra, 256x256, 125855 kb/s
Info: ,
Info: 60 fps,
Info: 1000k tbr,
Info: 1000k tbn
Info:

**Comment by LucasBosko** [comment]
Info: [gdigrab @ 0000014705f2d8c0] Capturing whole desktop as 256x256x32 at (832,412)

Info: Input #0, gdigrab, from 'desktop':

Info:   Duration:
Info: N/A
Info: , start:
Info: 1689720190.779734
Info: , bitrate:
Info: 125855 kb/s
Info:

Info:   Stream #0:0
Info: : Video: bmp, bgra, 256x256, 125855 kb/s
Info: ,
Info: 60 fps,
Info: 1000k tbr,
Info: 1000k tbn
Info:
