### ISSUE TITLE
how can i fix this??

### ISSUE THREAD

**Issue by ek271** [Jire/Overwatcheat#296]
[main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/C:/Users/marko/Downloads/Overwatcheat-5.1.0/build/Overwatcheat%205.1.0/Overwatcheat%205.1.0.jar
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/foreign/MemorySession
        at org.jire.overwatcheat.nativelib.User32Panama.<clinit>(User32Panama.kt:26)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.<init>(ToggleUIThread.kt:29)
        at org.jire.overwatcheat.Main.main(Main.kt:73)
Caused by: java.lang.ClassNotFoundException: java.lang.foreign.MemorySession
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more

**Comment by Takefive320** [comment]
You should Uninstall jdk and install jdk-19.
