### ISSUE TITLE
It works but....

### ISSUE THREAD

**Issue by lollerbay** [Jire/Overwatcheat#303]
It works but it tracks towards the right foot of the target, am I doing something wrong? if I change my screen resolution to 720p and ingame resolution to 720p as well it targets the enemies properly but its slow and jittery no matter what setting I change please note that on normal resolution that is 1080p it tracks good and responds to change in settings but it targets the foot of the enemies.

windows 11 22h2 
overwatcheat 5.1.0 no error
using frame grab from "desktop"
NOTE: only ingame only Fullscreen works with "desktop" nothing else

**Comment by 2fersen** [comment]
The original config is for a "2560x1440" so change it to this or fullhd

**Comment by Robzerix** [comment]
using "desktop" frame grab for me -
[main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/C:/Users/Robzerix/Downloads/Overwatcheat-5.1.0/Overwatcheat-5.1.0/build/Overwatcheat%205.1.0/Overwatcheat%205.1.0.jar
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/foreign/MemorySession
        at org.jire.overwatcheat.nativelib.User32Panama.<clinit>(User32Panama.kt:26)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.<init>(ToggleUIThread.kt:29)
        at org.jire.overwatcheat.Main.main(Main.kt:73)
Caused by: java.lang.ClassNotFoundException: java.lang.foreign.MemorySession
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 3 more
Press any key to continue . . .

**Comment by 2fersen** [comment]
Wait, you are using fullscreen mode? You should use borderless window frame, but anyways, the cheat isnt that good. you Can have just settings for one range, its working pretty good on midrange, but absolutly not on wide-range or nearby targets. For me its working better to train the aim, instead of hopping the aimbot snaps

**Comment by Robzerix** [comment]
doesnt seem to work still
[main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/C:/Users/Robzerix/Downloads/Overwatcheat-5.1.0/Overwatcheat-5.1.0/build/Overwatcheat%205.1.0/Overwatcheat%205.1.0.jar
[Aim Bot] INFO net.openhft.affinity.AffinityLock - Assigning cpu 6 to Thread[#42,Aim Bot,9,main] on thread id 11032
[Aim Bot] WARN net.openhft.affinity.impl.WindowsJNAAffinity - Tried to set affinity to {6} but was {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11} you may have in sufficient access rights
Info: [gdigrab @ 000002b92bab1b00] Capturing whole desktop as 256x256x32 at (1152,592)

Info: Input #0, gdigrab, from 'desktop':

Info:   Duration:
Info: N/A
Info: , start:
Info: 1696656952.739227
Info: , bitrate:
Info: 346101 kb/s
Info:

Info:   Stream #0:0
Info: : Video: bmp, bgra, 256x256, 346101 kb/s
Info: ,
Info: 165 fps,
Info: 1000k tbr,
Info: 1000k tbn
Info:
