### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/foreign/MemorySession

### ISSUE THREAD

**Issue by waa344** [Jire/Overwatcheat#309]
Can anyone help me I'm not very good with PC's so this all makes no sense to me:

[main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/C:/Users/willw/Downloads/Overwatcheat-5.1.0/Overwatcheat-5.1.0/build/Overwatcheat%205.1.0/Overwatcheat%205.1.0.jar
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/foreign/MemorySession
        at org.jire.overwatcheat.nativelib.User32Panama.<clinit>(User32Panama.kt:26)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.<init>(ToggleUIThread.kt:29)
        at org.jire.overwatcheat.Main.main(Main.kt:73)
Caused by: java.lang.ClassNotFoundException: java.lang.foreign.MemorySession
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 3 more
Press any key to continue . . .

**Comment by gasthell** [comment]
Try java19, I encountered the same problem, it can be solved with java19, someone gave this method before
https://www.oracle.com/java/technologies/javase/jdk19-archive-downloads.html

**Comment by EdLovecraft** [comment]
use jdk 19, only 19 works

**Comment by edvn991** [comment]
> use jdk 19, only 19 works

Is that really all?

**Comment by Chinaholmesfans** [comment]
C:\Users\xxx>java -version
java version "19" 2022-09-20
Java(TM) SE Runtime Environment (build 19+36-2238)
Java HotSpot(TM) 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)

I face the same problem and Im sure I m using jdk19
