### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by moharfe** [Jire/Overwatcheat#310]
Exception in thread "Aim Bot" java.lang.ExceptionInInitializerError         at org.jire.overwatcheat.Mouse.<clinit>(Mouse.kt:34)         at org.jire.overwatcheat.aimbot.AimBotThread.performAim(AimBotThread.kt:137)         at org.jire.overwatcheat.aimbot.AimBotThread.useAimData(AimBotThread.kt:106)         at org.jire.overwatcheat.aimbot.AimBotThread.run(AimBotThread.kt:79) Caused by: java.lang.IllegalArgumentException: Cannot open library: interception         at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:235)         at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:199)         at org.jire.overwatcheat.nativelib.interception.Interception.<clinit>(Interception.kt:26)         ... 4 more

**Comment by moharfe** [comment]
![image](https://github.com/Jire/Overwatcheat/assets/88576025/23a04195-744f-4876-9145-36557b53c9a6)
