### ISSUE TITLE
Exception in thread "Toggle UI" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by SgtDragon** [Jire/Overwatcheat#313]
This is the exceptions I'm getting, am testing in the training area on tracer.

Exception in thread "Toggle UI" java.lang.ExceptionInInitializerError
        at org.jire.overwatcheat.Keyboard.pressKey(Keyboard.kt:49)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.toggleUI(ToggleUIThread.kt:44)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.run(ToggleUIThread.kt:35)
Caused by: java.lang.IllegalArgumentException: Cannot open library: interception
        at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:235)
        at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:199)
        at org.jire.overwatcheat.nativelib.interception.Interception.<clinit>(Interception.kt:26)
        ... 3 more

**Comment by asifimran422** [comment]
I am facing the same problem. !!!! Any solution?


[main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/D:/Softwares/Overwatcheat-5.1.0/Overwatcheat-5.1.0/build/Overwatcheat%205.1.0/Overwatcheat%205.1.0.jar
[Aim Bot] INFO net.openhft.affinity.AffinityLock - Assigning cpu 2 to Thread[#42,Aim Bot,9,main] on thread id 9744
[Aim Bot] WARN net.openhft.affinity.impl.WindowsJNAAffinity - Tried to set affinity to {2} but was {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11} you may have in sufficient access rights
Info: [gdigrab @ 00000222dfd5bb40] Found window Overwatch, capturing 256x256x32 at (832,412)

Info: Input #0, gdigrab, from 'title=Overwatch':

Info:   Duration:
Info: N/A
Info: , start:
Info: 1718885238.231239
Info: , bitrate:
Info: 62927 kb/s
Info:

Info:   Stream #0:0
Info: : Video: bmp, bgra, 256x256, 62927 kb/s
Info: ,
Info: 30 fps,
Info: 1000k tbr,
Info: 1000k tbn
Info:

Exception in thread "Toggle UI" java.lang.ExceptionInInitializerError
        at org.jire.overwatcheat.Keyboard.pressKey(Keyboard.kt:49)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.toggleUI(ToggleUIThread.kt:44)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.run(ToggleUIThread.kt:35)
Caused by: java.lang.IllegalArgumentException: Cannot open library: interception
        at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:235)
        at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:199)
        at org.jire.overwatcheat.nativelib.interception.Interception.<clinit>(Interception.kt:26)
        ... 3 more

**Comment by Flowing8175** [comment]
find interception.dll file in the Interception driver folder, then put it in ...\Overwatcheat 5.1.0\build\Overwatcheat 5.1.0\ folder.

In case that doesn't work, copy all files of the driver .dll, .lib, .h files, and put it in all these directories:

...\Overwatcheat 5.1.0\build\Overwatcheat 5.1.0\
...\Overwatcheat 5.1.0\build\lib (it could be somewhere else, but you know)


that should help.

**Comment by MrBear9021** [comment]
Same problem, where can I find interception.dll file?
