### ISSUE TITLE
Error upon opening overwatch cheat 5.1.0

### ISSUE THREAD

**Issue by eizendrach** [Jire/Overwatcheat#315]
![image](https://github.com/Jire/Overwatcheat/assets/160060956/ff0779e2-bb38-49f5-a01c-2b3c1cbae82f)

Priorly stated that [main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/C:/Users/User/Downloads/Overwatcheat-5.1.0/Overwatcheat-5.1.0/build/Overwatcheat%205.1.0/Overwatcheat%205.1.0.jar
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/foreign/MemorySession
at org.jire.overwatcheat.nativelib.User32Panama.(User32Panama.kt:26)
at org.jire.overwatcheat.aimbot.ToggleUIThread.(ToggleUIThread.kt:29)
at org.jire.overwatcheat.Main.main(Main.kt:73)
Caused by: java.lang.ClassNotFoundException: java.lang.foreign.MemorySession
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
... 3 more
Press any key to continue . . .

Did a little bit of tinkering and now it doesn't state anything. All steps have been followed properly, using jdk19

**Comment by Najeraq** [comment]
did you got it working?

**Comment by eizendrach** [comment]
> did you got it working?

Yeah i did. I don't remember what i did anymore tho.
