### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by firas5000** [Jire/Overwatcheat#320]
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/foreign/MemorySession
        at org.jire.overwatcheat.nativelib.User32Panama.<clinit>(User32Panama.kt:26)
        at org.jire.overwatcheat.aimbot.ToggleUIThread.<init>(ToggleUIThread.kt:29)
        at org.jire.overwatcheat.Main.main(Main.kt:73)
Caused by: java.lang.ClassNotFoundException: java.lang.foreign.MemorySession
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 3 more

**Comment by Flowing8175** [comment]
you're on wrong jdk version, use 19 or another (i remember it's 19)
