### ISSUE TITLE
Error - 5

### ISSUE THREAD

**Issue by Danama507** [Jire/Overwatcheat#58]
It was working earlier but now it wont. PLease help.

**Comment by ghoulkiddoo** [comment]
So what that means is you are being screen locked, if you try taking a screen shot with Lightbox all you would get is a black screen. I have been trying to figure out a way to bypass it for a couple days now, as someone who has never coded before and is learning all of this as their doing it, it gets hard. I have tried to bypass it by disallowing ScreenLock to be used in windows, and running it in win 7 compatibility mode, I've tried to use the OBS trick and none of it worked. The last thing I have yet to successfully try is re-naming the OBS full screen projector to Overwatch and running the aimbot, I have renamed it successfully, but when I try to run the aimbot it says `[gdigrab @ 00000000002ac1e0] Capture area (951,538),(970,543) extends outside window area (0,0),(221,50)Capture area (951,538),(970,543) extends outside window area (0,0),(221,50)Exception in thread "main" org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -5: Could not open input "title=Overwatch". (Has setFormat() been called?)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:535)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:465)
        at com.overwatcheat.Overwatcheat.main(Overwatcheat.kt:66)`

I am at a loss of what to do, if @Jire or @Lonew0lfe has any way of helpping it would be appreciated, but I have a feeling they are done with helping.
