### ISSUE TITLE
correctly compiled but exceptions on running

### ISSUE THREAD

**Issue by piggydoggie** [Jire/Overwatcheat#67]
Yo bro, that's what i get when i try to launch the .bat in the build folder.

What's the clue?

`Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property windowTitle has not been initialized
        at com.overwatcheat.nativelib.HWNDFinder.access$getWindowTitle$p(HWNDFinder.kt:25)
        at com.overwatcheat.nativelib.HWNDFinder$projectorWindowTitle$2.invoke(HWNDFinder.kt:40)
        at com.overwatcheat.nativelib.HWNDFinder$projectorWindowTitle$2.invoke(HWNDFinder.kt:25)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.overwatcheat.nativelib.HWNDFinder.getProjectorWindowTitle(HWNDFinder.kt)
        at com.overwatcheat.Overwatcheat.main(Overwatcheat.kt:68)`

**Comment by piggydoggie** [comment]
Edit: 

- game is in windowed full screen mode
- correctly have jdk jdre 8 installed + path variables

**Comment by wow1wow2** [comment]
same error here! have you found a way to fix this?

**Comment by JohnSilver2077** [comment]
The same error please help me

**Comment by JohnSilver2077** [comment]
JDK and JRE have been installed correctly. There is no problem with Java configuration path. The game also uses full screen windowing
![image](https://user-images.githubusercontent.com/81319791/112347685-09df1d00-8d02-11eb-9bf6-239701594661.png)

**Comment by JohnSilver2077** [comment]
[gdigrab @ 000001acba00b5c0] Found window OBS 26.1.1 (64-bit, windows) - �����: Fullscreen Projector - ����: Fullscreen Projector, capturing 426x432x32 at (747,324)
Input #0, gdigrab, from 'title=OBS 26.1.1 (64-bit, windows) - �����: Fullscreen Projector - ����: Fullscreen Projector':
  Duration: N/A, start: 1616608646.601111, bitrate: 353367 kb/s
    Stream #0:0: Video: bmp, bgra, 426x432, 353367 kb/s, 60 fps, 1000k tbr, 1000k tbn, 1000k tbc

This interface appears after installing OBS, but an error will be reported
