### ISSUE TITLE
"main" java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by WhoR3born** [Jire/Overwatcheat#71]
`Exception in thread "main" java.lang.NoSuchMethodError: kotlin.jvm.internal.Intrinsics$Kotlin.intArrayOf([I)[I
        at com.overwatcheat.Settings$Companion.read(Settings.kt:48)
        at com.overwatcheat.Settings$Companion.read(Settings.kt:36)
        at com.overwatcheat.Settings$Companion.read$default(Settings.kt:36)
        at com.overwatcheat.Overwatcheat.main(Overwatcheat.kt:59)
Press any key to continue . . .
`
build was succesfull. jdk and interception driver installed.

**Comment by Jire** [comment]
Try version 3.1.0, although this error seems strange.

**Comment by WhoR3born** [comment]
> 
> 
> Try version 3.1.0, although this error seems strange.

still getting same error :(

**Comment by 1881pac** [comment]
> > Try version 3.1.0, although this error seems strange.
> 
> still getting same error :(
Did you find a solution?
