### ISSUE TITLE
Start Overwatcheat 3.4.1.bat   Run error

### ISSUE THREAD

**Issue by 153317974** [Jire/Overwatcheat#76]
[gdigrab @ 0000021e3019d7c0] Capture area (832,412),(1088,668) extends outside window area (0,0),(144,20)Capture area (832,412),(1088,668) extends outside window area (0,0),(144,20)Exception in thread "Frame Grabber" org.bytedeco.javacv.FFmpegFrameGrabber$Exception: avformat_open_input() error -5: Could not open input "title=GitHub - Jire/Overwatcheat: Free, open-source undetected color cheat! - Google Chrome". (Has setFormat() been called?) (For more details, make sure FFmpegLogCallback.set() has been called.)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:921)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:846)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:841)
        at com.overwatcheat.framegrab.FrameGrabberThread.run(FrameGrabberThread.kt:30)

**Comment by 194328373** [comment]
我也是这个问题，你解决了吗

**Comment by xzqaaa** [comment]
好像是没有捕捉到Overwatch这个名字，改用obs的全屏投影即可解决
google translate：It seems that the name Overwatch is not captured, and it can be solved by using the full-screen projection of obs
