### ISSUE TITLE
No error during build but it gives me this error message when starting it

### ISSUE THREAD

**Issue by DeadlyShadow71** [Jire/Overwatcheat#79]
Exception in thread "Aim Bot" java.lang.UnsatisfiedLinkError: Unable to load library 'interception':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/interception.dll) not found in resource path ([file:/E:/Overwatch/Overwatcheat-3.4.1/build/Overwatcheat%203.4.1/Overwatcheat%203.4.1.jar])
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
        at com.overwatcheat.nativelib.DirectNativeLib.<init>(DirectNativeLib.kt:27)
        at com.overwatcheat.nativelib.interception.Interception.<init>(Interception.kt:25)
        at com.overwatcheat.nativelib.interception.Interception.<clinit>(Interception.kt:25)
        at com.overwatcheat.Mouse.<clinit>(Mouse.kt:36)
        at com.overwatcheat.aimbot.AimBotThread.useAimData(AimBotThread.kt:80)
        at com.overwatcheat.aimbot.AimBotThread.run(AimBotThread.kt:47)
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
                ... 8 more
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
                ... 8 more
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:264)
                ... 8 more
        Suppressed: java.io.IOException: Native library (win32-x86-64/interception.dll) not found in resource path ([file:/E:/Overwatch/Overwatcheat-3.4.1/build/Overwatcheat%203.4.1/Overwatcheat%203.4.1.jar])
                at com.sun.jna.Native.extractFromResourcePath(Native.java:1096)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
                ... 8 more

**Comment by JackMeds** [comment]
How did you fix it

**Comment by DeadlyShadow71** [comment]
I was a dumbass and didn't watch the video explaining the installation process, I neither had the interception driver installed nor had the .dll in the folder so that's why I got the error. Just follow the video step by step and don't be like me and you won't get the error.

**Comment by JackMeds** [comment]
> I was a dumbass and didn't watch the video explaining the installation process, I neither had the interception driver installed nor had the .dll in the folder so that's why I got the error. Just follow the video step by step and don't be like me and you won't get the error.

Me too, but after I do all this, the mouse doesn't seem to aim at the target

**Comment by DeadlyShadow71** [comment]
Do you have a mouse button 5? If not, just rebind the aim key to something else, just look up "VK_CODES" and look through the list
