### ISSUE TITLE
Capture area (832,412),(1088,668) extends outside window area (0,0),(0,0)

### ISSUE THREAD

**Issue by Gr0gn4k** [Jire/Overwatcheat#89]
[gdigrab @ 000001a16edbe940] Capture area (832,412),(1088,668) extends outside window area (0,0),(0,0)Capture area (832,412),(1088,668) extends outside window area (0,0),(0,0)Exception in thread "Frame Grabber" org.bytedeco.javacv.FFmpegFrameGrabber$Exception: avformat_open_input() error -5: Could not open input "title=Overwatch". (Has setFormat() been called?) (For more details, make sure FFmpegLogCallback.set() has been called.)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:921)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:846)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:841)
        at com.overwatcheat.framegrab.FrameGrabberThread.run(FrameGrabberThread.kt:30)

**Comment by Gr0gn4k** [comment]
I do not understand this

**Comment by deceased1** [comment]
did u fix?
